sudo: false
language: python
dist: xenial

cache:
  pip: true

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8-dev"
      env: TOXENV=py38
  allow_failures:
    - python: "3.8-dev"
      env: TOXENV=py38
  # fast_finish: true

install:
  - pip install -r requirements.txt

script:
  - make test

after_success:
  - coveralls
